"""Status constants for Exp40 MiniMax PSNR-safe rescue."""

EXP40_BRANCH = "research/exp40-minimax-psnr-safe-rescue-20260628"

STATUS_READBACK = "EXP40_READBACK_COMPLETED"
STATUS_R1_SIGNAL_AUDITED = "MINIMAX_R1_SIGNAL_AUDITED"
STATUS_DATA_PENDING = "MINIMAX_LOCALDPO_V3_POOL_PENDING"
STATUS_SFT_PENDING = "MINIMAX_SFT_PSNRSAFE_PENDING"

FORBIDDEN_CLAIMS = {
    "UNIVERSAL_ADAPTER",
    "ALL_MODELS_SUPPORTED",
    "FINAL_SOTA",
    "TOP_CONFERENCE_NOVELTY_CONFIRMED",
}


def current_status() -> str:
    return STATUS_READBACK
